/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlQueriesRouteImport } from './routes/sql-queries'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EcgRouteImport } from './routes/ecg'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SqlQueriesRoute = SqlQueriesRouteImport.update({
  id: '/sql-queries',
  path: '/sql-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EcgRoute = EcgRouteImport.update({
  id: '/ecg',
  path: '/ecg',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/ecg': typeof EcgRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/sql-queries': typeof SqlQueriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/ecg': typeof EcgRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/sql-queries': typeof SqlQueriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/ecg': typeof EcgRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/sql-queries': typeof SqlQueriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ecg'
    | '/login'
    | '/patients'
    | '/predictions'
    | '/reports'
    | '/sql-queries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ecg'
    | '/login'
    | '/patients'
    | '/predictions'
    | '/reports'
    | '/sql-queries'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ecg'
    | '/login'
    | '/patients'
    | '/predictions'
    | '/reports'
    | '/sql-queries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  EcgRoute: typeof EcgRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  PredictionsRoute: typeof PredictionsRoute
  ReportsRoute: typeof ReportsRoute
  SqlQueriesRoute: typeof SqlQueriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql-queries': {
      id: '/sql-queries'
      path: '/sql-queries'
      fullPath: '/sql-queries'
      preLoaderRoute: typeof SqlQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecg': {
      id: '/ecg'
      path: '/ecg'
      fullPath: '/ecg'
      preLoaderRoute: typeof EcgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  EcgRoute: EcgRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  PredictionsRoute: PredictionsRoute,
  ReportsRoute: ReportsRoute,
  SqlQueriesRoute: SqlQueriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
